# Generated by Django 4.1.6 on 2023-02-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['-date_added'], name='forum_entry_date_ad_f159fb_idx'),
        ),
    ]
