# Generated by Django 4.1.6 on 2023-02-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_entry_slug_entry_title_topic_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='about',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=40),
        ),
    ]
